const UNAUTHORIZED_REQUEST_ERROR = "UNAUTHORIZED_REQUEST_ERROR";

const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";

const BAD_REQUEST_ERROR = "BAD_REQUEST_ERROR";

module.exports = {
    UNAUTHORIZED_REQUEST_ERROR,
    INTERNAL_SERVER_ERROR,
    BAD_REQUEST_ERROR
};
